# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

# security configuration (this key should be unique for your application, and kept secret)
jhipster.security.rememberme.key: ime

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

spring:
    mail:
        host: localhost
        port: 25
        user:
        password:
        protocol: smtp
        tls: false
        auth: false
        from: ime@localhost

    messageSource:
        cacheSeconds: 1

authentication:
    oauth:
        clientid: imeapp
        secret: mySecretOAuthSecret
        # Token is valid 30 minutes
        tokenValidityInSeconds: 1800

swagger:
    title: Capella IME API

